market_sonar/analysis/urls.py
from django.urls import path
from . import views

app_name='stock'

urlpatterns = [
    path('news',views.News,name="news"),
    path('stock',views.stock_prediction,name="graph"),
    path('socio',views.socio,name="socio"),
    path('feedback',views.feedback,name="feedback"),

    ]

market_sonar/blog/urls.py
from . import views
from django.urls import path
app_name='blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

market_sonar/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.Landingpage,name="landing"),
    path('register',views.Register,name="Register"),
    path('login',views.Login,name="Login"),
    path('logout',views.Logout,name='logout')
]

market_sonar/market_sonar/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('analysis/',include("analysis.urls")),
    path('blog/', include('blog.urls')),
   
   
]

market_sonar/analysis/models.py
from django.db import models
from home.models import Client

# Create your models here.
class stockdata(models.Model):        
    symbol=models.CharField(max_length=12)
    date=models.DateField(null=False)

class feedback(models.Model):
    user=models.ForeignKey(Client, on_delete=models.CASCADE)
    feedback=models.TextField(null=False,blank=False)

market_sonar/analysis/views.py
from django.shortcuts import render
from .models import stockdata 
from .models import feedback as fd
from home.models import Client
from django.shortcuts import redirect
from django.urls import reverse
from django.views.decorators.cache import cache_control

# Create your views here.
import numpy as np
from nsepy import get_history
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import plotly.offline as opy
import plotly.graph_objects as go

from newsapi import NewsApiClient
import pandas as pd
from django.shortcuts import redirect
from nltk.sentiment.vader import SentimentIntensityAnalyzer


import datetime as dt
import snscrape.modules.twitter as sntwitter
import re
import matplotlib.pyplot as plt
import io
import urllib,base64



#-----------------------------Prediction and Graph-------------------------------------------------------------------------------------

def News(req):
    if(req.session.is_empty()): 
        
        req.session.set_expiry(0)      
        return render(req,'home/login.html') 
        
    else:
        total_score=0
        AVG=0
        newsapi = NewsApiClient(api_key='4e0ef55dfc634f40961b7249ae0128cf')
        News=[]
        vade=SentimentIntensityAnalyzer()
        if req.method=='POST':
            symbol=f"{req.POST['symbol']}"
            articles = newsapi.get_everything(q=symbol,
                                      language='en',
                                      sort_by='relevancy')
            
        else:          
            articles = newsapi.get_top_headlines(                                         
                                                category='business',
                                                language='en',
                                                country='in')
            
            
        for x in articles['articles']:
            score=((vade.polarity_scores(x['title'])['compound']+1)/2)*100
            total_score=total_score+score
            News.append([x['publishedAt'][:10],x['title'],score])
        l=len(articles['articles'])
            #df=pd.DataFrame(News,columns=['date','title'])
        AVG=total_score/l
        print(l)
        context={'d':News,'av':AVG}
        return render(req,'analysis/news.html',context)
        
def stocklist():
    df=pd.read_csv("analysis/stockdata/equity.csv")
    nse_list=df["SYMBOL"].tolist()
    return(nse_list)



def stock_prediction(req):
    if(req.session.is_empty()):
        
        req.session.set_expiry(0) 
        return render(req,'login.html') 
    else:
        if req.method == 'POST':
            symbol=f"{req.POST['symbol']}"
        else:
            symbol='TCS'
            
        import datetime 
        
        stock=stockdata()
        import math
        start=datetime.date(2020,1,1)
        end=datetime.date.today()
        st=stockdata.objects.filter(symbol=symbol)
        loc=f"analysis/stockdata/{symbol}.csv"
        
        if st.count()==1:
            for i in st:
                if i.date==datetime.date.today():
                    pass
                else:
                    df=pd.read_csv(loc)
                    lastdate=datetime.datetime.strptime(df['Date'].max(),"%Y-%m-%d")
                    print(type(lastdate))
                    start=lastdate.date()+datetime.timedelta(days = 1)
                    data=get_history(symbol=symbol, start=start , end=end)
                    data.to_csv(loc,mode='a',index=True,header=False)
                    i.date=datetime.date.today()
                    i.save()
                    
        else:
            data=get_history(symbol=symbol, start=start , end=end)
            data.to_csv(loc)
            stock.symbol=symbol
            stock.date=datetime.date.today()
            stock.save()
            
               
        df=pd.read_csv(loc)
        df=df.set_index('Date')
        data=df.filter(["Close"])
        dataset=data.values
        training_data_len=math.ceil(len(dataset)*0.8)
        scaler=MinMaxScaler(feature_range=(0,1))
        scaled_data=scaler.fit_transform(dataset)
        train_data=scaled_data[0:training_data_len,:]
        x_train = []
        y_train = []
        for i in range(60, len(train_data)):
            x_train.append(train_data[i-60:i, 0])
            y_train.append(train_data[i, 0])
        x_train, y_train = np.array(x_train), np.array(y_train)
        x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
        model = Sequential()
        model.add(LSTM(50, return_sequences = True, input_shape = (x_train.shape[1], 1)))
        model.add(LSTM(50, return_sequences = False))
        model.add(Dense(25))
        model.add(Dense(1))
        model.compile(optimizer = 'adam', loss = 'mean_squared_error')
        model.fit(x_train, y_train, batch_size = 1, epochs = 1)
        test_data = scaled_data[training_data_len - 60: , :]
        x_test = []
        y_test = dataset[training_data_len:, :]
        for i in range (60, len(test_data)):
             x_test.append(test_data[i - 60:i, 0])

        x_test = np.array(x_test)
        x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
        predictions = model.predict(x_test)
        predictions = scaler.inverse_transform(predictions)
        train = data[:training_data_len]
        valid = data[training_data_len:]
        valid.insert(1,'predictions',predictions)
        last_60_days = data[-60:].values
        last_60_days_scaled = scaler.transform(last_60_days)
        X_test = []
        X_test.append(last_60_days_scaled)
        X_test = np.array(X_test)
        X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1], 1))
        pred_price = model.predict(X_test)
        pred_price = scaler.inverse_transform(pred_price)
        
        fig = go.Figure()
        fig.add_trace(go.Scatter(x = train.index, y = train['Close'],
                            mode='lines',
                            name='Close',
                            marker_color = '#1F77B4'))
        fig.add_trace(go.Scatter(x = valid.index, y = valid['Close'],
                            mode='lines',
                            name='Val',
                            marker_color = '#FF7F0E'))
        fig.add_trace(go.Scatter(x = valid.index, y = valid.predictions,
                            mode='lines',
                            name='Predictions',
                            marker_color = '#2CA02C'))

        fig.update_layout(
            title=symbol,
            titlefont_size = 28,
            hovermode = 'x',
            xaxis = dict(
                title='Date',
                titlefont_size=16,
                tickfont_size=14),
            
            height = 800,
            
            yaxis=dict(
                title='Close price in INR (₹)',
                titlefont_size=16,
                tickfont_size=14),
            legend=dict(
                y=0,
                x=1.0,
                bgcolor='rgba(255, 255, 255, 0)',
                bordercolor='rgba(255, 255, 255, 0)'))

        div=opy.plot(fig,auto_open=False,output_type='div')
        nse_list=stocklist()
        context={'list':nse_list,'graph':div,'price':pred_price}
        return render(req,'analysis/graph.html',context)

def socio(req):
    if(req.session.is_empty()):
        
        req.session.set_expiry(0) 
        return redirect('home:Login')
    else:
        if req.method == 'POST':
            symbol=f"{req.POST['symbol']}"
            print(symbol)
        else:
            symbol='INDIA'
            
    query = symbol
    noOfTweet = 1000
    noOfDays = 7
            
    #Creating list to append tweet data
    tweets_list = []
    now = dt.date.today()
    now = now.strftime('%Y-%m-%d')
    yesterday = dt.date.today() - dt.timedelta(days = int(noOfDays))
    yesterday = yesterday.strftime('%Y-%m-%d')
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query + ' lang:en since:' +  yesterday + ' until:' + now + ' -filter:links -filter:replies').get_items()):
        if i > int(noOfTweet):
            break
        tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.username])
    df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])
    df["Text"] = df["Text"].apply(cleanTxt)
    positive = 0
    negative = 0
    neutral = 0
    #Creating empty lists
    tweet_list1 = []
    neutral_list = []
    negative_list = []
    positive_list = []

    #Iterating over the tweets in the dataframe
    for tweet in df['Text']:
        tweet_list1.append(tweet)
        analyzer = SentimentIntensityAnalyzer().polarity_scores(tweet)
        neg = analyzer['neg']
        neu = analyzer['neu']
        pos = analyzer['pos']
        comp = analyzer['compound']

        if neg > pos:
            negative_list.append(tweet) #appending the tweet that satisfies this condition
            negative += 1 #increasing the count by 1
        elif pos > neg:
            positive_list.append(tweet) #appending the tweet that satisfies this condition
            positive += 1 #increasing the count by 1
        elif pos == neg:
            neutral_list.append(tweet) #appending the tweet that satisfies this condition
            neutral += 1 #increasing the count by 1 

    positive = percentage(positive, len(df)) #percentage is the function defined above
    negative = percentage(negative, len(df))
    neutral = percentage(neutral, len(df))
    #Converting lists to pandas dataframe
    tweet_list1 = pd.DataFrame(tweet_list1)
    neutral_list = pd.DataFrame(neutral_list)
    negative_list = pd.DataFrame(negative_list)
    positive_list = pd.DataFrame(positive_list)
    #using len(length) function for counting
    labels = ['Positive ['+str(round(positive))+'%]' , 'Neutral ['+str(round(neutral))+'%]','Negative ['+str(round(negative))+'%]']
    sizes = [positive, neutral, negative]

market_sonar/analysis/templates/analysis/acc_aside.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<!-- <head>

</head> -->
<head>
  function showLoaderOnClick(url) {
    showLoader();
    window.location=url;
}
function showLoader(){
    $('body').append('<div style="" id="loadingDiv"><div class="loader">Loading...</div></div>');
}
</head>

<body>

<!-- <header>

</header> -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{% url 'stock:news' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Stock</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'stock:news' %}">
              <i class="bi bi-circle"></i><span>News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'stock:graph' %}">
              <i class="bi bi-circle"></i><span>Prediction</span></a>
              
            </a>
          </li>
          <li>
            <a href="{% url 'stock:socio' %}">
              <i class="bi bi-circle"></i><span>Social Sentiment</span></a>
              
            </a>
          </li>
        </ul>
      </li>
      <!-- End Components Nav -->
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Feedback and Complains</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'stock:feedback' %}">
              <i class="bi bi-circle"></i><span>Send Feedback</span>
            </a>
          </li>
        </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link collapsed"  href="{% url 'blog:blog' %}" target="_blank">
              <i class="bi bi-menu-button-wide"></i><span>Ideas and Blog</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
           </li>
          
      <!-- End Forms Nav -->

      <!-- End Tables Nav -->

      <li class="nav-heading">Pages</li>

      

  </aside><!-- End Sidebar-->

  <!-- main start -->

  {% block content %}
  {% endblock %}
  <!-- End #main -->

  <!-- Vendor JS Files -->

  <!-- Template Main JS File -->
 

</body>
</html>

market_sonar/analysis/templates/analysis/acc_header.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<body>
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="/newindex/" class="logo d-flex align-items-center">
        <img src="assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">Market Sonar</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <!-- <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div> -->
    <!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">4</span>
          </a><!-- End Notification Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have 4 new notifications
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-exclamation-circle text-warning"></i>
              <div>
                <h4>Lorem Ipsum</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>30 min. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

           
            <li class="dropdown-footer">
              <a href="#">Show all notifications</a>
            </li>

          </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have 3 new messages
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

           
            <li class="message-item">
              <a href="#">
                <img src="assets/img/messages-3.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>David Muldon</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>8 hrs. ago</p>
                </div>
              </a>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="dropdown-footer">
              <a href="#">Show all messages</a>
            </li>

          </ul><!-- End Messages Dropdown Items -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{req.session.name}}</h6>
              <span>User</span>
            </li>


              <li>
              <hr class="dropdown-divider">
            </li>

            
            <li>
              <hr class="dropdown-divider">
            </li>

            
            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'home:logout' %}" onclick = setTimeout(function() {
                rating();
            }, 100);>
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
                            
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header>
   <!-- ======= Footer ======= -->
   <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>Market Sonar</span></strong>. All Rights Reserved
    </div>
    
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->

  <!-- Template Main JS File -->

</body>

</html>

market_sonar/analysis/templates/analysis/ad_head.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
    <title>Dashboard - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
  
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">
  
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/styleadmin.css' %}" rel="stylesheet">
  
</head>

   <!-- Vendor JS Files -->
   <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
   <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
   <script src="{% static 'assets/vendor/chart.js/chart.min.js' %}"></script>
   <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
   <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
   <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
   <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
   <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
 
   <!-- Template Main JS File -->
   <script src="{% static 'assets/js/main.js' %}"></script>
</html>

market_sonar/analysis/templates/analysis/feedback.html
{% include "analysis/acc_aside.html" %}
{% include "analysis/acc_header.html" %}
{% include "analysis/ad_head.html" %}
{% load static %}
{% block content %}
<main id="main" class="main">
    

      <form action="{% url 'stock:feedback' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label>Please Enter your Feedback here</label>
            <textarea class="form-control" id="T1" rows="3" name='T1'></textarea>
          </div>

        <input type="submit" value="submit" class="btn-create" name="submit">
    </form>
</main>
{% endblock %}

market_sonar/analysis/templates/analysis/graph.html
{% include "analysis/acc_aside.html" %}
{% include "analysis/acc_header.html" %}
{% include "analysis/ad_head.html" %}
{% load static %}
{% block content %}
<main id="main" class="main">

    <form action="{% url 'stock:graph' %}" method="POST">
        {% csrf_token %}
        <input list="symbol" placeholder="Enter Stock Symbol" name="symbol">
        <datalist id="symbol">
            {% if list %}
            {% for i in list %}
            <option value={{i}}>{{i}}</option>
            {% endfor %}
            {% endif %}
        </datalist>

        <input type="submit" value="submit" class="btn-create" name="submit">
    </form>
{% if price %}
<div style="width:600;height:500">
<p>predicted price = {{price.0.0}}</p>
</div>
{% else %}
<p>No graph was provided.</p>
{% endif %}
{% if graph %}
<div style="width:600;height:500">
{{ graph|safe }}
</div>
{% else %}
<p>No graph was provided.</p>
{% endif %}

</main>
{% endblock %}

market_sonar/analysis/templates/analysis/js_inc.html
<script src="{% static 'tellme/feedback.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $.feedback({
            ajaxURL: "{% url 'tellme:post_feedback' %}",
            html2canvasURL: "{% static 'tellme/html2canvas.min.js' %}",
            feedbackButton: "#feedback-btn",
            initButtonText: "{% filter escapejs %}{%  include 'tellme/initButtonText.txt' %}{% endfilter %}",
            postHTML: false,
            tpl: {
                description: "{% filter escapejs %}{%  include 'tellme/tpl-description.html' %}{% endfilter %}",
                highlighter: "{% filter escapejs %}{%  include 'tellme/tpl-highlighter.html' %}{% endfilter %}",
                            overview:        "{% filter escapejs %}{%  include 'tellme/tpl-overview.html' %}{% endfilter %}",
                            submitSuccess:"{% filter escapejs %}{%  include 'tellme/tpl-submit-success.html' %}{% endfilter %}",
                            submitError: "{% filter escapejs %}{%  include 'tellme/tpl-submit-error.html' %}{% endfilter %}"
            },
            initialBox: true
        });
    });
</script>

market_sonar/analysis/templates/analysis/news.html
{% include "analysis/acc_aside.html" %}
{% include "analysis/acc_header.html" %}
{% include "analysis/ad_head.html" %}
{% load static %}
{% block content %}


<main id="main" class="main">
  <form action="{% url 'stock:news' %}" method="POST">
    {% csrf_token %}
    <input list="symbol" placeholder="Enter Stock Symbol" name="symbol">
    <datalist id="symbol">
        {% if list %}
        {% for i in list %}
        <option value={{i}}>{{i}}</option>
        {% endfor %}
        {% endif %}
    </datalist>

    <input type="submit" value="submit" class="btn-create" name="submit">
</form>

     <div class="container">
        <h2 class="text-center"><u>NEWS</u></h2><br> 
        {% if av %}
        <div style="width:600;height:500">
        <p>AVG = {{av}}</p>
        </div>
        {% else %}
        <p>No avg</p>
        {% endif %}        
        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th>Date</th>
              <th>NEWS</th>
              <th>SENTIMENT</th>
            </tr>
        </thead>
        <tbody>
         {% if d %}
         {% for i in d %}
         <tr>
           <style>
             .progress{
               height:200px;
               position:relative;
               background: #4a9fad;
                }
              .progress:after{
                content: '\A';
                position:absolute;
                background: red;
                top:0;
                bottom: 0;
                left:0;
                width: '{{i.2}}';

              }
           </style>
            
              <td>{{i.0}}</td>
              <td>{{i.1}}</td>  
              <td>{{i.2}}</td>          
            
        </tr>
        {% endfor %}
        {% endif %}
        </tbody>
      </table>
    </div>
</main><!-- End #main -->

{% endblock %}

market_sonar/analysis/templates/analysis/socio.html
{% include "analysis/acc_aside.html" %}
{% include "analysis/acc_header.html" %}
{% include "analysis/ad_head.html" %}
{% load static %}
{% block content %}
<main id="main" class="main">

  <form action="{% url 'stock:socio' %}" method="POST">
    {% csrf_token %}
    <input list="symbol" placeholder="Enter Stock Symbol" name="symbol">
    <datalist id="symbol">
        {% if list %}
        {% for i in list %}
        <option value={{i}}>{{i}}</option>
        {% endfor %}
        {% endif %}
    </datalist>

    <input type="submit" value="submit" class="btn-create" name="submit">
</form>
    <body>
        <img src="data:image/png;base64,{{ data }}" alt="" height="400" ,width="400">
      </body>
</main>
{% endblock %}