market_sonar/blog/urls.py
from . import views
from django.urls import path
app_name='blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

market_sonar/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.Landingpage,name="landing"),
    path('register',views.Register,name="Register"),
    path('login',views.Login,name="Login"),
    path('logout',views.Logout,name='logout')
]

market_sonar/market_sonar/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('analysis/',include("analysis.urls")),
    path('blog/', include('blog.urls')),
   
   
]

market_sonar/home/models.py
from django.db import models

# Create your models here.


# Create your models here.
class Client(models.Model):
    Active=1
    InActive=0
    user_status=[
        (Active,'active'),
        (InActive,'inactive'),
    ]
    user=1
    Expert=0
    user_role=[
        (user,"USER"),
        (Expert,'EXPERT')
    ]
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=35)
    email=models.CharField(max_length=50)
    mobile=models.CharField(max_length=12)
    uname=models.CharField(max_length=15)
    password=models.CharField(max_length=30)
    role=models.PositiveSmallIntegerField(default=1,choices=user_role)
    status=models.PositiveSmallIntegerField(default=1,choices=user_status)

market_sonar/home/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import *
from django.shortcuts import render
from  .models import Client
from django.shortcuts import redirect
# Create your views here.

def Landingpage(req):
    return render(req,'home/landing.html')

#-------------------------------------------------------

def Login(req):
    #cred=users.objects.all()
    if req.method == 'POST':
        username=req.POST['uname']
        password=req.POST['password']
        cred=Client.objects.filter(uname=username,password=password,status=1)
        if cred.count()==1:
            for i in cred:
                id=i.id
            req.session['id']=id 
            return redirect("stock:news")       
        else:
            messages.error(req, f"Login failed")
            return HttpResponse(f"Login Failed Try again")
        
    return render(req,'home/login.html')


    #------------------------------------------------------------------


def Register(req):
    duplication_set=set()
    user_details=Client.objects.all()
    for individual in user_details:
        duplication_set.add(individual.uname)
        duplication_set.add(individual.email)
        duplication_set.add(individual.mobile)

    if req.method == 'POST':
        mob=req.POST['mob']
        email=req.POST['email']
        uname=req.POST['uname']
        password=req.POST['pass']
        pass1=req.POST['pass1']
        usr=Client()
        if uname=='' or email=='' or mob==''  or password=='' or pass1=='':
            messages.info(req,'please fill all fields')
        elif mob not in duplication_set and email not in duplication_set and uname not in duplication_set:

            usr.name= req.POST['name']
            usr.email= req.POST['email']
            usr.mobile= req.POST['mob']
            usr.uname= req.POST['uname']
            usr.password= req.POST['pass']
            
            if password != pass1:
                messages.error(req, f"passwords doesnt match")
        
            else:
                usr.save()
                return render(req,'home/login.html')
        else:
            if mob in duplication_set:
                messages.error(req, f"Mobile already registered")
            elif email in duplication_set:
                messages.error(req, f"email already registered")
            else:
                messages.error(req, f"username already registered")
        print(duplication_set)

    return render(req,'home/register.html')

    #-------------------------------------------------------------------------

def Logout(req):
    req.session.flush()
    return redirect("home:Login")

market_sonar/home/templates/home/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Market Sonar-Stock analysis</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>

    <!-- header section starts  -->

    <header class="header">

        <a href="#" class="logo"> <i class='bx bx-money-withdraw'></i> Market Sonar </a>

        <nav class="navbar">
            <a href="#home">Home</a>
            <a href="#products">About</a>
            <a href="#categories">Contact</a>
            <a href="{% url 'home:Login' %}">Login</a>
            <a href="{% url 'home:Register' %}">Register</a>
        </nav>
        <form action="" class="search-form">
            <input type="search" id="search-box" placeholder="search here...">
            <label for="search-box" class="fas fa-search"></label>
        </form>
    </header>

    <!-- header section ends -->

    <!-- home section starts  -->

    <section class="home" id="home">

        <div class="content">
            <h3>We <span> Analyze </span> Market for you</h3>
            <p>Get Quick briefings and stock predictions</p>
            <a href="{% url 'home:Login' %}" class="btn">Login</a>
        </div>

    </section>

    <!-- home section ends -->

    <!-- features section starts  -->

    <section class="features" id="features">

        <h1 class="heading"> What we do for <span>YOU</span> </h1>

        <div class="box-container">

            <div class="box">
                <img src="{{STATIC_URL}}image/feature-img-1.png" alt="">
                <h3>Stock predictions</h3>
                <p>We provide you with predictions of stock price using the best in industry algorithms</p>
            </div>

            <div class="box">
                <img src="{{STATIC_URL}}image/feature-img-2.png" alt="">
                <h3>News analysis
                </h3>
                <p>We analysis the sentiments of Business News for your quick decisions</p>
            </div>

            <div class="box">
                <img src="{{STATIC_URL}}image/feature-img-3.png" alt="">
                <h3>Get Recommendations</h3>
                <p>We provide you with recommendations of stocks for you to trade or invest</p>
            </div>

        </div>

    </section>

    <!-- features section ends -->

    <!-- categories section starts  -->

   

    <!-- categories section ends -->

    <!-- review section starts  -->
    <section class="review" id="review">

        <h1 class="heading"> Are you a <span>Market Expert</span> </h1>

        <div class="swiper review-slider">

            <div class="swiper-wrapper">

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-1.png' %}" alt="">
                    <p>Are you an experienced trader/ invester, be with us to create a better solution for market enthusiasts</p>
                    <a href="{% url 'home:Login' %}" class="btn">Join with us</a>
                </div>
            </div>
        </div>
    </section>

    <section class="review" id="review">

        <h1 class="heading"> User <span>review</span> </h1>

        <div class="swiper review-slider">

            <div class="swiper-wrapper">

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-1.png' %}" alt="">
                    <p>Market Sonar helps us to select stocks fast and know about market sentiments fast. The predictions also provide the confidence for newbies to trade.</p>
                    <h3>john deo</h3>
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star-half-alt"></i>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- review section ends -->

    <!-- footer section starts  -->

    <section class="footer">

        <div class="box-container">

            <div class="box">
                <h3> Market Sonar <i class='bx bx-money-withdraw'></i> </h3>
                <p>All rights reserved.connect us with </p>
                <div class="share">
                    <a href="#" class="fab fa-facebook-f"></a>
                    <a href="#" class="fab fa-twitter"></a>
                    <a href="#" class="fab fa-instagram"></a>
                    <a href="#" class="fab fa-linkedin"></a>
                </div>
            </div>
        </div>
    </section>

    <!-- footer section ends -->


</body>

</html>

market_sonar/home/templates/home/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% if messages %}
        {% for message in messages %}
          <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
        {% endfor %}
    {% endif %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100&family=Poppins:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/formstyle.css' %}">
<script type="text/javascript">
    function valid()
    {
        var name= document.myform.uname.value;
        var pass= document.myform.password.value;

        if(name=='')
        {
        alert("please enter your name");
        return false;
        }
    
        if(pass=='')
        {
        
            alert("please enter your password");
            return false;
        }
        return true;
    }
</script>



</head>
<body>
    <main>
        <div class="box">
            <div class="inner-box">
                <div class="column-1">
                    <img src="{% static 'image/logo.png' %}" alt="" class="logo">
                    <div class="desc">
                    Market Sonar
                    </div>
                    <img src="{% static 'image/initial.png' %}" alt="" class="image">
                </div>
                <div class="column-2">
                    <form class="form" name="myform" action="{% url 'home:Login' %}" method="POST" onsubmit="return(valid())">
                        {% csrf_token %}
                        
                        <h3>Login</h3>
                        <div class="inputs">
                            <div class="input-field">
                                <input type="text" class="input" placeholder="UserName" name='uname'>
                            </div>
                            
                            <div class="input-field">
                                <input type="password" class="input pass" placeholder="Password"  name='password'>
                            </div>
                            <input type="submit" value="Login" class="btn-create">
                        </div>

                        <div class="login">Don't have an account?
                            <a href="{% url 'home:Register' %}">Register</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/form.js' %}"></script>

</body>
</html>

market_sonar/home/templates/home/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% if messages %}
        {% for message in messages %}
          <script> alert('Username already exist'); </script>
        {% endfor %}
  {% endif %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup Form</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100&family=Poppins:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/formstyle.css' %}">
    <script type="text/javascript">
      function validate() {
            var name = document.myform.name.value;            
            var email = document.myform.email.value;
            var mobile = document.myform.mob.value;
            var uname = document.myform.uname.value;
            var pwd = document.myform.pass.value;
            var cpwd = document.myform.pass1.value;
            
            var pwd_expression = /^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{7,15}$/;
            var letters = /^[A-Za-z]+$/;
            var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            var phoneno = /^\d{10}$/;


            if (name == '') {
                alert('Please enter your name');
                return false;
            } else if (!letters.test(name)) {
                alert('Name must contain alphabet characters only');
                return false;
            } 
            else if (email == '') {
                alert('Please enter your user email id');
                return false;
            } else if (!filter.test(email)) {
                alert('Invalid email');
                return false;
            } else if (mobile == '') {
                alert('Please enter the mobile number.');
                return false;
            } else if (!phoneno.test(mobile)) {
                alert('Invalid Phoneno');
                return false;
            } else if (uname == '') {
                alert('Please enter the username.');
                return false;
            } else if (pwd == '') {
                alert('Please enter your Password');
                return false;
            } else if (!pwd_expression.test(pwd)) {
                alert('7 to 15 characters which contain at least one numeric digit and a special character  are required in Password filed');
                return false;
            } else if (cpwd == '') {
                alert('Enter Confirm Password');
                return false;
            } else if (pwd != cpwd) {
                alert('Password not Matched');
                return false;
            } else {
                alert('Registration Sucessfully');
            }
            return (true);

        }
  </script>
</head>

<body>
    <main>
        <div class="box">
            <div class="inner-box">
                <div class="column-1">
                    <img src="{% static 'image/logo.png' %}" alt="" class="logo">
                    <div class="desc">
                    Market Sonar
                    </div>
                    <img src="{% static 'image/initial.png' %}" alt="" class="image">
                </div>
                <div class="column-2">
                    <form class="form"  name="myform" action="{% url 'home:Register' %}" method="POST" onsubmit="return(validate());">
                        {% csrf_token %}
                        
                        <h3>create account</h3>
                        <div class="inputs">
                            <div class="input-field">
                                <input type="text" class="input" placeholder="Name"  name="name">
                            </div>
                             <div class="input-field">
                                <input type="email" class="input" placeholder="Email"  name="email">
                            </div>
                            <div class="input-field">
                                <input type="text" class="input" placeholder="Mobile"  name="mob">
                            </div>
                            <div class="input-field">
                                <input type="text" class="input" placeholder="Username"  name="uname">
                            </div>
                            <div class="input-field">
                                <input type="password" class="input pass" placeholder="Password"  name="pass">
                            </div>
                            <div class="input-field">
                                <input type="password" class="input pass" placeholder="Confirm Password"  name="pass1">
                            </div>
                            <input type="submit" value="submit" class="btn-create" name="submit">
                        </div>

                        <div class="login">Already a User
                            <a href="{% url 'home:Login' %}">Login Here</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/form.js' %}"></script>
</body>
</html>